# Generated by Django 3.2.5 on 2021-07-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
                ('Publication_year', models.IntegerField()),
                ('genre', models.CharField(max_length=240)),
                ('language', models.CharField(max_length=290)),
                ('Book_description', models.TextField()),
            ],
        ),
    ]
