# Generated by Django 3.2.5 on 2021-07-14 08:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=13),
        ),
    ]
